import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Inputfield from '../components/input Fields/input'
import Choicebox from '../components/input Fields/choice'
import Dropdown from '../components/input Fields/dropdown'
import Step01 from '../components/forms/transcript form/step1_transaction_info'
import Step02 from '../components/forms/transcript form/step2_personal_info'
const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Proguide</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="stylesheet" href="https://unicons.iconscout.com/release/v4.0.0/css/line.css"></link>
        <link rel="stylesheet" href="https://unicons.iconscout.com/release/v4.0.0/css/solid.css"></link>
        <link rel="stylesheet" href="https://unicons.iconscout.com/release/v4.0.0/css/thinline.css"></link>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Proguide 2.0 components view
        </h1>

        <p className={styles.description}>
          built with ❤️ & ☕ by
          <code className={styles.code}>proguideteam</code>
        </p>

        <div className={styles.grid}>
          
        <div className="p-2">
          <Choicebox id={''} options={['Fast Mode','Super Fast Mode']}/>
          <Step01/>
        </div>
        <div className="ml-2">
          <Step02/>

        </div>
        

          
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
